export const SET_CHANGE = 'SET_CHANGE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_MOBILE = 'SET_MOBILE'
export const SET_USERID = 'SET_USERID'
export const SET_HEAD = 'SET_HEAD'
